#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
// change the following paths if necessary
if (file_exists(dirname(__FILE__).'/web/env.php')){
	$envInit = include_once dirname(__FILE__).'/web/env.php';//??????
}

defined('YII_ENV') or define('YII_ENV', !empty($envInit['env']) ? $envInit['env'] : 'prod');
defined('YII_DEBUG') or define('YII_DEBUG', (stripos(YII_ENV, 'dev') !== false));

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
